name: document_qa
description: Document Q&A with RAG
version: 1.0.0
workflow_type: rag_chain
steps:
  - name: retrieve
    type: retrieval
    config:
      vector_store: pgvector
      top_k: 5
      similarity_threshold: 0.7
      rerank: true
  
  - name: generate
    type: llm_call
    config:
      model: gpt-4
      temperature: 0.1
      max_tokens: 1000

prompts:
  system: "system/document_qa_system.j2"
  user: "user/document_qa_user.j2"

tools:
  - name: sql_tool
    enabled: false
  - name: api_tool
    enabled: false

memory:
  type: conversation_buffer
  max_tokens: 2000

token_budget: 10000
max_retries: 3
timeout_seconds: 300
